Development to radar view
stronnag/mwptools pull request #111
Opened 2021-11-28 21:14 UTC by wx4cb

this allows for an altitude limit to the radar list view settable in meters via the schema xml.

2021-11-28 21:37 UTC, stronnag requested changes
Please also remove the  `mwp-plot-elevation` binary from the PR. This file is not kept in the repository.

2021-11-28 21:37 UTC, stronnag commented on src/mwp/mwp.vala
> +        MWPLog.message("Maximum Altitude set to: %u\n", conf.max_radar_altitude);
* This would be better protected by `DEBUG_FLAGS.RADAR` otherwise it will be confusing to the majority of user who don't use radar functions
* The debug should also include context "RDR: Maxiumum ... "

2021-11-28 21:37 UTC, stronnag commented on src/mwp/mwp.vala
> +                MWPLog.message("Not listing %s at %.lf m\n", ri.name, ri.altitude);
The debug should also include context "RDR: Not ... "

2021-11-28 21:37 UTC, stronnag commented on src/mwp/org.mwptools.planner.gschema.xml
> +      <description>Maximum altitude (meters) to show hits in the radar list view
mwp uses English / European spelling, the SI units are "metres", not "meters". Please also replace the 30000 feet with a suitable description in metres (e.g. 10000m) .

2021-11-28 21:37 UTC, stronnag commented on src/mwp/settings.vala
> +// CB - 11.25.21 - add a max altitude variable with a default of 10000m
There's no need to initial comments, the git history provides that detail. The comment can be removed (it's also erroneous, the default is set to 5000m, not 10000).

2021-11-28 21:41 UTC, wx4cb commented
> Please also remove the `mwp-plot-elevation` binary from the PR. This file is not kept in the repository.

not sure how to do this. ended up having two commits. tried to edit the commit, but couldnt figure it out, as for the others i'll work on the inconsistancy

2021-11-28 21:42 UTC, wx4cb commented on src/mwp/settings.vala
> +// CB - 11.25.21 - add a max altitude variable with a default of 10000m
force of habit

2021-11-28 22:04 UTC, wx4cb commented
@stronnag check it now, but i think i screwed it up. not sure

2021-11-29 20:34 UTC, stronnag commented on src/mwp/mwp.vala
> +                                        radarv.update(r, conf.dms);
This breaks the compilation, it's now missing
```
	if (r.altitude < conf.max_radar_altitude) {
```
so the `{}` are no longer matched.

2021-11-29 20:39 UTC, stronnag requested changes
You still need to remove the mwp-plot elevations binary (slightly "mea culpa" as `ninja clean` doesn't delete it), however you must have (erroneously) used `git add`  on it.
Now, in the top level:

```
git rm src/mwp-plot-elevations/mwp-plot-elevations
```
fix the missing line c. mwp.vala:5002
```
git commit -a -m 'fix review comments'
```
and we should be done .... I hope.

2021-11-29 20:52 UTC, wx4cb commented on src/mwp/mwp.vala
> +                                        radarv.update(r, conf.dms);
done

2021-11-29 20:53 UTC, wx4cb commented
ok i ddi those changes and the git commands, hopefully that works. don't think i need to try a PR right ? it should automagically show up here now I pushed it to my repo?

2021-11-29 21:21 UTC, stronnag approved these changes

2021-11-29 21:22 UTC, merged